# global architecture params
dtype: float32
param_dtype: float32
token_embedding_dim: 768 
dropout_rate: 0.1
attention_dropout_rate: 0.0

# describe the input sequence modalities and number of tokens
input_sequence: "[TaskDescriptionPrefix{16}] [Image{25};Readout{7}]*2"
tokens_per_task_description: 16
tokens_per_image: 25
tokens_per_readout: 7
num_observation_blocks: 2

# action head prediction settings
forward_method: predict_action_logits
prediction_type: categorical

defaults:
  - tokenizers/text: t5_base
  - tokenizers/images: gato_resnet
  - tokenizers/readouts: octo
  - attention_blocks: vanilla_decoder
  - action_heads: categorical

