num_epochs: 30
batch_size: 6

# checkpoint manager
checkpoint_dir: ${config.project.base_path}/.checkpoints/${config.wandb.experiment_name}/transporter_pick
max_checkpoints: 10
save_interval: 5

optimizer:
  _target_: optax.adam
  learning_rate: 1e-4
