FROM ghcr.io/peterdavidfagan/jax_container:latest

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

# Copy the project files for building virtual environment
COPY . /app

# Set the working directory
WORKDIR /app

# Install dependencies
RUN poetry install
