FROM ubuntu:jammy

# install basic dependencies
RUN apt-get update && apt-get install -y \
    curl \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

# Copy the project files for building virtual environment
COPY . /app

# Set the working directory
WORKDIR /app

# Install dependencies
RUN poetry install
