dataset: colour_splitter
tfds_data_dir: /media/peter/400cb321-2b54-4ffc-a661-2d49ca87dfaf/transporter_datasets
shuffle_buffer_size: 10
batch_size: ${config.training.transporter_pick.batch_size}

huggingface:
  entity: peterdavidfagan
  repo: transporter_networks_mujoco
  files:
    - colour_splitter_2024-05-08-12:35:43.tar.gz
  
crop:
  u_min: 0
  u_max: 640
  v_min: 0
  v_max: 480
