num_epochs: 1000
batch_size: 4

# checkpoint manager
checkpoint_dir: ${config.project.base_path}/.checkpoints/${config.wandb.experiment_name}/transporter_place
max_checkpoints: 8
save_interval: 10

optimizer:
  _target_: optax.adam
  learning_rate: 1e-4
