name: robot-learning-baselines-train

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"
  pull_request:
  push:
    branches: ['main']
    paths:
      - robot_learning_baselines/**

env:
  REGISTRY: ghcr.io
  ORG_NAME: peterdavidfagan
  IMAGE_NAME: robot-learning-baselines-train

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}
      
      - name: Free Space
        run: |
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf ${GITHUB_WORKSPACE}/.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          df -h
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/train_job_jax/Dockerfile.train_job
          push: true
          no-cache: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
